const appRoot = document.getElementById('app');
const toastEl = document.getElementById('toast');
const state = { user: null, csrf: '', employeeCache: [], theme: localStorage.getItem('peopleos-theme') === 'dark' ? 'dark' : 'light', adminSetupAvailable: false, adminExists: false, companyName: '' };
document.documentElement.classList.toggle('theme-dark', state.theme === 'dark');
const statuses = ['Active', 'On Leave', 'Resigned', 'Terminated'];
const esc = (v='') => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials = (v='?') => String(v).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
function canonicalPath(path) {
  if (path === '/') return state.user?.role === 'admin' ? '/admin/dashboard' : state.user ? '/employee/dashboard' : '/employee/login';
  if (path === '/login') return '/employee/login';
  if (path === '/dashboard') return '/admin/dashboard';
  if (path === '/employees') return '/admin/employees';
  if (path === '/employees/new') return '/admin/employees/new';
  if (path.startsWith('/employees/')) return path.replace('/employees/', '/admin/employees/');
  if (path === '/profile') return state.user?.role === 'employee' ? '/employee/profile' : '/profile';
  if (path === '/register') return '/employee/login';
  return path;
}
const route = () => canonicalPath(location.pathname);
function go(path) { const target=canonicalPath(path); history.pushState({}, '', target); render(); window.scrollTo(0,0); }
function toast(message) { toastEl.textContent=message; toastEl.classList.add('show'); setTimeout(()=>toastEl.classList.remove('show'),2800); }
function themeToggle(){const dark=state.theme==='dark';return `<button class="theme-toggle" id="theme-toggle" type="button" aria-pressed="${dark}" aria-label="Switch to ${dark?'light':'dark'} mode" title="Switch to ${dark?'light':'dark'} mode">${dark?'☀ Light mode':'☾ Dark mode'}</button>`;}
function bindThemeToggle(){document.getElementById('theme-toggle')?.addEventListener('click',()=>{state.theme=state.theme==='dark'?'light':'dark';document.documentElement.classList.toggle('theme-dark',state.theme==='dark');try{localStorage.setItem('peopleos-theme',state.theme);}catch{}const button=document.getElementById('theme-toggle');if(button){const dark=state.theme==='dark';button.textContent=dark?'☀ Light mode':'☾ Dark mode';button.setAttribute('aria-pressed',String(dark));button.setAttribute('aria-label',`Switch to ${dark?'light':'dark'} mode`);button.title=`Switch to ${dark?'light':'dark'} mode`;}});}
async function api(path, options={}) {
  const headers={'Content-Type':'application/json',...(options.headers||{})};
  if (['POST','PUT','DELETE','PATCH'].includes(options.method)) headers['X-CSRF-Token']=state.csrf;
  const response=await fetch(path,{credentials:'same-origin',...options,headers});
  const data=await response.json().catch(()=>({error:'The server returned an invalid response.'}));
  if(!response.ok){const error=new Error(data.error||'Something went wrong.');error.status=response.status;throw error;}
  return data;
}
async function initialize(){
  try { const me=await api('/api/me'); state.user=me.user; state.csrf=me.csrf_token; }
  catch { try { const csrf=await fetch('/api/csrf',{credentials:'same-origin'}).then(r=>r.json());state.csrf=csrf.csrf_token;}catch{} }
  try { const setup=await fetch('/api/admin/setup-status',{credentials:'same-origin'}).then(r=>r.json());state.adminSetupAvailable=Boolean(setup.available);state.adminExists=Boolean(setup.has_admin);state.companyName=setup.company_name||''; } catch {}
  if(state.user && ['/login','/employee/login','/admin/login','/admin/register','/register','/'].includes(location.pathname)) go(state.user.role==='admin'?'/admin/dashboard':'/employee/dashboard');
  else render();
}
function shell(content, current) {
  const admin=state.user?.role==='admin';
  const links=admin?[['/admin/dashboard','◫','Dashboard'],['/admin/employees','▤','Employees'],['/admin/employees/new','＋','Add employee'],['/settings','⚙','Settings']]:[['/employee/dashboard','◫','Dashboard'],['/employee/profile','◉','My profile']];
  const active=(p)=>current===p||(p==='/admin/employees'&&current.startsWith('/admin/employees/')&&current!=='/admin/employees/new');
  return `<div class="shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">P</div><div>PeopleOS<small>EMPLOYEE MANAGEMENT</small></div></div><div class="nav-label">Workspace</div><nav class="nav">${links.map(([href,icon,label])=>`<a href="${href}" class="${active(href)?'active':''}" data-go="${href}"><span class="ico">${icon}</span>${label}</a>`).join('')}</nav><div class="side-spacer"></div><div class="nav-label">Account</div><nav class="nav"><a href="#" id="logout-link"><span class="ico">↪</span>Logout</a></nav><div class="profile-chip"><div class="avatar">${initials(state.user.full_name)}</div><div><strong>${esc(state.user.full_name)}</strong><small>${admin?'Administrator':'Employee'}</small></div></div></aside><main class="main"><header class="topbar"><div class="top-right"><button class="mobile-menu" id="menu-toggle" aria-label="Open menu">☰</button><span class="crumb">Workspace&nbsp; / &nbsp;<strong>${esc(current.split('/').filter(Boolean).map(x=>x==='new'?'Add employee':x[0]?.toUpperCase()+x.slice(1)).join(' / ')||'Dashboard')}</strong></span></div><div class="top-right">${themeToggle()}<span class="today">${new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',year:'numeric'}).format(new Date())}</span><div class="avatar">${initials(state.user.full_name)}</div></div></header><section class="content">${content}</section></main></div>`;
}
function authLayout(content, title, subtitle){return `<div class="auth-page"><section class="auth-brand"><div class="brand"><div class="brand-mark">P</div><div>PeopleOS<small>EMPLOYEE MANAGEMENT</small></div></div><div class="auth-copy"><h1>Good people.<br>Great work.</h1><p>A thoughtful workspace to manage your team, keep records organized, and help people do their best work.</p><div class="auth-points"><div class="auth-point"><span class="check">✓</span> One secure place for your employee records</div><div class="auth-point"><span class="check">✓</span> Clear roles and private profiles</div><div class="auth-point"><span class="check">✓</span> Built for teams that keep growing</div></div></div><div class="auth-foot">© ${new Date().getFullYear()} PeopleOS · Employee Management</div></section><section class="auth-form-side">${themeToggle()}<div class="auth-form"><h2>${title}</h2><p>${subtitle}</p>${content}</div></section></div>`;}
function loginPage(){const admin=route()==='/admin/login';const mode=admin?'admin':'employee';const signupNote=admin&&state.adminSetupAvailable?`<div class="auth-switch"><a href="/admin/register" data-go="/admin/register">${state.adminExists?'Create Admin Account':'Create First Admin Account'}</a></div>`:admin?'<div class="auth-switch">Admin sign-up is unavailable right now.</div>':'<div class="auth-switch">Employee accounts are created by your administrator.</div>';return authLayout(`<div class="auth-roles"><a class="${admin?'':'selected'}" href="/employee/login" data-go="/employee/login">Employee Login</a><a class="${admin?'selected':''}" href="/admin/login" data-go="/admin/login">Admin Login</a></div><div class="error-banner" id="form-error"></div><form id="login-form" data-login-role="${mode}"><div class="field"><label for="email">${admin?'Admin Email':'Work Email'}</label><input id="email" name="email" type="email" autocomplete="username" placeholder="${admin?'admin@example.com':'you@example.com'}" required></div><div class="field"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" placeholder="Enter your password" required></div><button class="btn btn-primary" type="submit">Sign in as ${admin?'admin':'employee'} <span>→</span></button></form>${signupNote}`,admin?'Admin Login':'Employee Login',admin?'Sign in with an administrator account.':'Sign in with your employee account.');}
function adminRegistrationPage(){if(!state.adminSetupAvailable)return authLayout(`<div class="note">Admin sign-up is unavailable. Return to the Admin Login page and try again.</div><div class="auth-switch"><a href="/admin/login" data-go="/admin/login">Return to Admin Login</a></div>`,'Admin Registration','Admin account setup is unavailable.');const first=!state.adminExists;return authLayout(`<div class="note" style="margin:0 0 16px">Administrator accounts have full access to employee records and workspace settings.</div><div class="error-banner" id="form-error"></div><form id="admin-register-form">${field('Full Name','name','','text',{required:true,max:120})}${field('Email','email','','email',{required:true,max:254})}${field('Password','password','','password',{required:true,max:128,min:8})}${field('Confirm Password','confirm_password','','password',{required:true,max:128,min:8})}<div class="hint">${first?'Create the first administrator account for this workspace.':'Create an administrator account.'} Use at least 8 characters for the password.</div><button class="btn btn-primary" type="submit">${first?'Create First Admin Account':'Create Admin Account'}</button></form><div class="auth-switch"><a href="/admin/login" data-go="/admin/login">Return to Admin Login</a></div>`,first?'First Admin Setup':'Admin Registration',first?'Create the first administrator for your PeopleOS workspace.':'Create your PeopleOS administrator account.');}
function stat(label,value,icon,cls,note){return `<article class="card stat"><div class="stat-top"><span>${label}</span><span class="stat-icon ${cls}">${icon}</span></div><strong>${value}</strong><small>${note}</small></article>`;}
function badge(status){const cls={'Active':'active','On Leave':'leave','Resigned':'resigned','Terminated':'terminated'}[status]||'resigned';return `<span class="badge badge-${cls}">${esc(status)}</span>`;}
function person(e){return `<div class="person"><div class="avatar">${initials(e.full_name)}</div><div><strong>${esc(e.full_name)}</strong><small>${esc(e.email)}</small></div></div>`;}
function tableRows(employees, actions=true){if(!employees.length)return `<tr><td colspan="7"><div class="empty">◷<strong>No employees found</strong>Try adjusting your search or filters.</div></td></tr>`;return employees.map(e=>`<tr><td><span class="code">${esc(e.employee_code)}</span></td><td>${esc(e.full_name)}</td><td>${esc(e.email)}</td><td>${esc(e.department)}</td><td>${esc(e.designation)}</td><td>${badge(e.employment_status)}</td><td>${actions?`<div class="actions"><button class="text-btn" data-view="${e.id}">View</button><button class="text-btn" data-edit="${e.id}">Edit</button><button class="text-btn" data-delete="${e.id}" style="color:#c85c5c">Delete</button></div>`:'<span class="muted">—</span>'}</td></tr>`).join('');}
async function dashboardPage(){
  let d;try{d=await api('/api/admin/dashboard');}catch(e){if(e.status===401){state.user=null;go('/admin/login');return'';}return `<div class="warning">${esc(e.message)}</div>`;}
  const max=Math.max(1,...d.departments.map(x=>x.count));
  return `<div class="page-head"><div><div class="eyebrow">${esc(state.companyName||'Company')} administration</div><h1>Admin Dashboard</h1><p>Organization overview and employee activity.</p></div><button class="btn btn-primary" data-go="/admin/employees/new">＋ &nbsp;Add employee</button></div><div class="grid stats">${stat('Total employees',d.total_employees,'♙','si-blue','Across your organization')}${stat('Active employees',d.active_employees,'✓','si-green','Currently working')}${stat('On leave',d.on_leave_employees,'◷','si-amber','Taking time off')}${stat('Departments',d.department_count,'▦','si-blue','Teams in your company')}</div><div class="grid dash-grid"><article class="card"><div class="card-head"><div><h2>Team by department</h2><p>Employee distribution across teams</p></div><span class="stat-icon si-green">▥</span></div><div class="chart-area">${d.departments.length?d.departments.map(x=>`<div class="bar-row"><span title="${esc(x.name)}">${esc(x.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(3,x.count/max*100)}%"></div></div><span class="bar-count">${x.count}</span></div>`).join(''):'<div class="empty">No department data yet.</div>'}</div></article><article class="card"><div class="card-head"><div><h2>Employment status</h2><p>Current workforce overview</p></div><span class="stat-icon si-amber">◉</span></div><div class="chart-area">${d.statuses.map((x,i)=>{let colors=['#19a88b','#dc9b36','#91a0ae','#d66060'];return `<div class="bar-row"><span>${esc(x.name)}</span><div class="bar-track"><div style="height:100%;width:${d.total_employees?Math.max(x.count?3:0,x.count/d.total_employees*100):0}%;background:${colors[i]};border-radius:6px"></div></div><span class="bar-count">${x.count}</span></div>`}).join('')}</div><div class="status-legend"><span><i class="dot" style="background:#19a88b"></i>Active</span><span><i class="dot" style="background:#dc9b36"></i>On leave</span><span><i class="dot" style="background:#91a0ae"></i>Resigned</span><span><i class="dot" style="background:#d66060"></i>Terminated</span></div></article></div><article class="card table-card"><div class="card-head"><div><h2>Recently added</h2><p>The latest additions to your team</p></div><button class="btn btn-light btn-small" data-go="/admin/employees">View directory →</button></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Position</th><th>Joining date</th><th>Status</th><th></th></tr></thead><tbody>${d.recent_employees.length?d.recent_employees.map(e=>`<tr><td>${person(e)}</td><td>${esc(e.department)}</td><td>${esc(e.designation)}</td><td>${formatDate(e.joining_date)}</td><td>${badge(e.employment_status)}</td><td><button class="text-btn" data-view="${e.id}">Details →</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No employee records yet.</div></td></tr>'}</tbody></table></div></article>`;
}
async function employeeDashboardPage(){let d;try{d=await api('/api/employee/dashboard');}catch(e){if(e.status===401){state.user=null;go('/employee/login');return '';}return `<div class="warning">${esc(e.message)}</div>`;}const e=d.employee;return `<div class="page-head"><div><div class="eyebrow">Employee workspace</div><h1>Employee Dashboard</h1><p>Welcome back, ${esc(d.user.full_name)}.</p></div><button class="btn btn-primary" data-go="/employee/profile">View my profile →</button></div>${e?`<div class="grid stats">${stat('Employee ID',esc(e.employee_code),'♙','si-blue','Your employee identifier')}${stat('Department',esc(e.department),'▦','si-green','Your team')}${stat('Position',esc(e.designation),'✦','si-blue','Your role')}${stat('Employment status',esc(e.employment_status),'✓','si-green','Current status')}</div><article class="card detail-card"><div class="eyebrow">My employment information</div><div class="details">${[['Full name',e.full_name],['Email',e.email],['Phone',e.phone],['Department',e.department],['Position',e.designation],['Joining date',formatDate(e.joining_date)]].map(([label,value])=>`<div class="detail-item"><small>${label}</small><strong>${esc(value)}</strong></div>`).join('')}</div></article>`:`<article class="card detail-card"><h2 style="font:700 15px Manrope">Employee record not linked yet</h2><p style="color:var(--muted)">Ask your administrator to create your employee record using ${esc(d.user.email)}. It will link to this login automatically.</p></article>`}`;}
function formatDate(v){if(!v)return'—';return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(v+'T00:00:00Z'));}
let listPage=1;
async function employeesPage(){
  const params=new URLSearchParams({page:String(listPage),per_page:'10'});const search=document.getElementById('employee-search')?.value||'';const dep=document.getElementById('department-filter')?.value||'';const status=document.getElementById('status-filter')?.value||'';if(search)params.set('search',search);if(dep)params.set('department',dep);if(status)params.set('status',status);
  let d;try{d=await api('/api/admin/employees?'+params);}catch(e){return `<div class="warning">${esc(e.message)}</div>`;}
  state.employeeCache=d.employees;
  return `<div class="page-head"><div><div class="eyebrow">People directory</div><h1>Employees</h1><p>Manage your people and their employment details.</p></div><button class="btn btn-primary" data-go="/employees/new">＋ &nbsp;Add employee</button></div><article class="card table-card"><div class="table-tools"><div class="searchbox"><span class="search-icon">⌕</span><input id="employee-search" placeholder="Search by name, code, email…" value="${esc(search)}"></div><select class="filter-select" id="department-filter"><option value="">All departments</option>${d.departments.map(x=>`<option ${x===dep?'selected':''} value="${esc(x)}">${esc(x)}</option>`).join('')}</select><select class="filter-select" id="status-filter"><option value="">All statuses</option>${statuses.map(x=>`<option ${x===status?'selected':''}>${x}</option>`).join('')}</select></div><div class="table-wrap"><table><thead><tr><th>Employee ID</th><th>Name</th><th>Email</th><th>Department</th><th>Position</th><th>Status</th><th>Actions</th></tr></thead><tbody>${tableRows(d.employees)}</tbody></table></div><div class="pagination"><span>Showing ${d.total?((d.page-1)*10+1):0}–${Math.min(d.page*10,d.total)} of ${d.total} employees</span><div><button id="prev-page" ${d.page<=1?'disabled':''}>← Previous</button><button id="next-page" ${d.page>=d.pages?'disabled':''}>Next →</button></div></div></article>`;
}
const field=(label,name,value='',type='text',opts={})=>`<div class="field ${opts.full?'full':''}"><label for="${name}">${label}${opts.required?'<em> *</em>':''}</label>${opts.select?`<select id="${name}" name="${name}" ${opts.required?'required':''}>${opts.options.map(o=>`<option value="${esc(o)}" ${o===value?'selected':''}>${esc(o||'Select '+label)}</option>`).join('')}</select>`:opts.textarea?`<textarea id="${name}" name="${name}" maxlength="500" placeholder="${esc(opts.placeholder||'')}">${esc(value||'')}</textarea>`:`<input id="${name}" name="${name}" type="${type}" value="${esc(value||'')}" ${opts.required?'required':''} ${opts.max?`maxlength="${opts.max}"`:''} ${opts.min?`minlength="${opts.min}"`:''} ${type==='number'?'min="0" step="0.01"':''}>`}</div>`;
function employeeForm(e={}){return `<div class="page-head"><div><div class="eyebrow">People directory</div><h1>${e.id?'Edit employee':'Add employee'}</h1><p>${e.id?'Update employment and contact details.':'Add a new record and employee login.'}</p></div><button class="btn btn-light" data-go="/employees">← &nbsp;Back to directory</button></div><article class="card form-card"><form id="employee-form" data-id="${e.id||''}"><div class="form-grid">${field('Employee ID','employee_code',e.employee_code||'','text',{required:true,max:32})}${field('Full name','full_name',e.full_name||'','text',{required:true,max:120})}${field('Work email','email',e.email||'','email',{required:true,max:254})}${field('Phone','phone',e.phone||'','tel',{required:true,max:32})}${field('Department','department',e.department||'','text',{required:true,max:80})}${field('Position','designation',e.designation||'','text',{required:true,max:100})}${field('Salary','salary',e.salary??'','number',{required:true})}${field('Joining date','joining_date',e.joining_date||'','date',{required:true})}${field('Employment status','employment_status',e.employment_status||'Active','text',{required:true,select:true,options:statuses})}${field('Temporary password','password','','password',{required:!e.id||!e.user_id,max:128})}${field('Gender','gender',e.gender||'','text',{max:30})}${field('Date of birth','date_of_birth',e.date_of_birth||'','date')}${field('Address','address',e.address||'','text',{full:true,textarea:true})}</div><div class="hint">A login is created with this password. Leave blank while editing to keep the current password.</div><div class="form-actions"><button class="btn btn-primary" type="submit">${e.id?'Save changes':'Create employee'}</button><button class="btn btn-light" type="button" data-go="/employees">Cancel</button><div class="error-banner" id="form-error" style="margin:0 0 0 8px"></div></div></form></article>`;}
async function detailPage(id){let e;try{e=(await api('/api/employees/'+id)).employee;}catch(err){return `<div class="warning">${esc(err.message)}</div><button class="btn btn-light" data-go="/employees">← Back</button>`;}return `<div class="page-head"><div><div class="eyebrow">People directory / Record</div><h1>Employee details</h1><p>Employment record and personal details.</p></div><div><button class="btn btn-light" data-go="/employees">← &nbsp;Back</button> <button class="btn btn-primary" data-edit="${e.id}">Edit record</button></div></div><div class="grid detail-grid"><article class="card detail-card"><div class="detail-person"><div class="avatar">${initials(e.full_name)}</div><div><h2>${esc(e.full_name)}</h2><p>${esc(e.designation)} · ${esc(e.department)}</p></div><div style="margin-left:auto">${badge(e.employment_status)}</div></div><div class="details">${[['Employee ID',e.employee_code],['Email',e.email],['Phone',e.phone],['Department',e.department],['Position',e.designation],['Joining date',formatDate(e.joining_date)],['Salary',new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(e.salary)],['Status',e.employment_status],['Gender',e.gender||'—'],['Date of birth',formatDate(e.date_of_birth)],['Address',e.address||'—']].map(([k,v])=>`<div class="detail-item"><small>${k}</small><strong>${esc(v)}</strong></div>`).join('')}</div></article><article class="card detail-card"><div class="eyebrow">Record information</div><h2 style="font:700 14px Manrope;margin:8px 0 20px">Employment timeline</h2><div class="detail-item"><small>Record created</small><strong>${formatDate(e.created_at?.slice(0,10))}</strong></div><hr class="section-sep"><div class="detail-item"><small>Last updated</small><strong>${formatDate(e.updated_at?.slice(0,10))}</strong></div><div class="note">This employee has a company-provided login for the employee portal.</div></article></div>`;}
async function profilePage(){if(state.user?.role==='admin')return `<div class="page-head"><div><div class="eyebrow">Administrator account</div><h1>My profile</h1><p>Your administrator account details.</p></div></div><article class="card detail-card" style="max-width:760px"><div class="detail-person"><div class="avatar">${initials(state.user.full_name)}</div><div><h2>${esc(state.user.full_name)}</h2><p>Administrator</p></div><span class="badge badge-active" style="margin-left:auto">Admin access</span></div><div class="details"><div class="detail-item"><small>Full name</small><strong>${esc(state.user.full_name)}</strong></div><div class="detail-item"><small>Email</small><strong>${esc(state.user.email)}</strong></div><div class="detail-item"><small>Role</small><strong>Administrator</strong></div></div><div class="note">Administrator accounts are managed separately and do not need an employee record. Use the Employees page to manage employee profiles.</div></article>`;let e;try{e=(await api('/api/profile')).employee;}catch(err){return `<div class="page-head"><div><div class="eyebrow">Self service</div><h1>My profile</h1><p>Your personal and employment information.</p></div></div><div class="warning">${esc(err.message)}${err.status===404?' An administrator can link your account when creating or editing your employee record.':''}</div>`;}return `<div class="page-head"><div><div class="eyebrow">Self service</div><h1>My profile</h1><p>Keep your contact details up to date.</p></div></div><div class="grid profile-layout"><article class="card profile-summary"><div class="avatar">${initials(e.full_name)}</div><h2>${esc(e.full_name)}</h2><p>${esc(e.designation)}</p>${badge(e.employment_status)}<div class="note">Your employee record is managed by your administrator. You can update your phone, address, and personal details.</div></article><article class="card form-card"><form id="profile-form"><div class="eyebrow">Personal details</div><div class="form-grid">${field('Full name','full_name',e.full_name,'text',{max:120})}${field('Work email','email',e.email,'email')}${field('Employee ID','employee_code',e.employee_code)}${field('Department','department',e.department)}${field('Position','designation',e.designation)}${field('Phone','phone',e.phone,'tel',{required:true,max:32})}${field('Date of birth','date_of_birth',e.date_of_birth||'','date')}${field('Gender','gender',e.gender||'','text',{max:30})}${field('Address','address',e.address||'','text',{full:true,textarea:true})}</div><div class="form-actions"><button class="btn btn-primary">Save profile</button></div><hr class="section-sep"><div class="eyebrow">Change password</div><div class="form-grid">${field('Current password','current_password','','password')}${field('New password','new_password','','password')}</div><div class="hint">Leave both password fields blank to keep your current password.</div><div class="error-banner" id="form-error" style="margin-top:14px"></div></form></article></div>`;}
function settingsPage(){return `<div class="page-head"><div><div class="eyebrow">Administrator account</div><h1>Settings</h1><p>Update your admin sign-in and manage trusted administrator accounts.</p></div></div><article class="card form-card" style="max-width:700px;margin-bottom:18px"><form id="admin-account-form"><div class="eyebrow">Change my admin login</div>${field('Admin email','email',state.user.email,'email',{required:true,max:254})}${field('Current password','current_password','','password',{required:true,max:128})}${field('New password (optional)','new_password','','password',{max:128})}${field('Confirm new password','confirm_password','','password',{max:128})}<div class="hint">Enter your current password to save. Leave both new password fields empty to keep your current password.</div><div class="error-banner" id="form-error" style="margin-top:14px"></div><div class="form-actions"><button class="btn btn-primary" type="submit">Save admin login</button></div></form></article><article class="card form-card" style="max-width:700px"><form id="admin-create-form"><div class="eyebrow">Add a company administrator</div><p style="color:var(--muted);font-size:12px">Create an additional administrator account. Only signed-in administrators can use this form.</p>${field('Company name','company_name',state.companyName||'PeopleOS','text',{required:true,max:160})}${field('Administrator name','name','','text',{required:true,max:120})}${field('Gmail or work email','email','','email',{required:true,max:254})}${field('Password','password','','password',{required:true,max:128,min:8})}${field('Confirm password','confirm_password','','password',{required:true,max:128,min:8})}<div class="hint">Use a unique email address and a password with at least 8 characters.</div><div class="error-banner" id="admin-create-error" style="margin-top:14px"></div><div class="form-actions"><button class="btn btn-primary" type="submit">Create administrator</button></div></form></article>`;}
async function render(){
  const path=route();
  if(!state.user){appRoot.innerHTML=route()==='/admin/register'?adminRegistrationPage():loginPage();bindAuth();return;}
  if(['/employee/login','/admin/login'].includes(path)){go(state.user.role==='admin'?'/admin/dashboard':'/employee/dashboard');return;}
  if(path.startsWith('/admin/')&&state.user.role!=='admin'){go('/employee/dashboard');return;}
  if(path.startsWith('/employee/')&&state.user.role!=='employee'){go('/admin/dashboard');return;}
  if(path==='/settings'&&state.user.role!=='admin'){go('/employee/dashboard');return;}
  if(!['/profile','/settings'].includes(path)&&!path.startsWith('/admin/')&&!path.startsWith('/employee/')){go(state.user.role==='admin'?'/admin/dashboard':'/employee/dashboard');return;}
  let html='';
  if(path==='/admin/dashboard')html=await dashboardPage();
  else if(path==='/employee/dashboard')html=await employeeDashboardPage();
  else if(path==='/admin/employees')html=await employeesPage();
  else if(path==='/admin/employees/new')html=employeeForm();
  else if(path.startsWith('/admin/employees/'))html=path.endsWith('/edit')?await editEmployeePage(path.split('/')[3]):await detailPage(path.split('/')[3]);
  else if(path==='/employee/profile'||path==='/profile')html=await profilePage();
  else if(path==='/settings')html=settingsPage();
  else {go(state.user.role==='admin'?'/admin/dashboard':'/employee/dashboard');return;}
  appRoot.innerHTML=shell(html,path);bindShell();bindPage(path);
}
async function editEmployeePage(id){try{return employeeForm((await api('/api/admin/employees/'+id)).employee);}catch(e){return `<div class="warning">${esc(e.message)}</div><button class="btn btn-light" data-go="/admin/employees">← Back to directory</button>`;}}
function showFormError(message){const box=document.getElementById('form-error');if(box){box.textContent=message;box.style.display='block';}}
function bindAuth(){bindThemeToggle();document.querySelectorAll('[data-go]').forEach(a=>a.addEventListener('click',ev=>{ev.preventDefault();go(a.dataset.go);}));const login=document.getElementById('login-form');if(login)login.addEventListener('submit',async ev=>{ev.preventDefault();try{const d=Object.fromEntries(new FormData(login));const expected=login.dataset.loginRole;const res=await api(expected==='admin'?'/api/admin/login':'/api/employee/login',{method:'POST',body:JSON.stringify(d)});state.user=res.user;state.csrf=(await api('/api/me')).csrf_token;go(state.user.role==='admin'?'/admin/dashboard':'/employee/dashboard');}catch(e){showFormError(e.message);}});const registration=document.getElementById('admin-register-form');if(registration)registration.addEventListener('submit',async ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(registration));if(data.password!==data.confirm_password){showFormError('Password confirmation does not match.');return;}try{const result=await api('/api/admin/register',{method:'POST',body:JSON.stringify(data)});state.user=result.user;state.csrf=result.csrf_token;state.companyName=result.company_name;state.adminExists=true;state.adminSetupAvailable=true;go('/admin/dashboard');}catch(error){showFormError(error.message);}});}
function bindShell(){bindThemeToggle();document.querySelectorAll('[data-go]').forEach(a=>a.addEventListener('click',ev=>{ev.preventDefault();go(a.dataset.go);}));document.getElementById('menu-toggle')?.addEventListener('click',()=>document.getElementById('sidebar').classList.toggle('open'));document.getElementById('logout-link')?.addEventListener('click',async ev=>{ev.preventDefault();const loginPath=state.user?.role==='admin'?'/admin/login':'/employee/login';try{await api('/api/logout',{method:'POST'});}catch{}state.user=null;state.csrf='';await fetch('/api/csrf',{credentials:'same-origin'}).then(r=>r.json()).then(d=>state.csrf=d.csrf_token);go(loginPath);});}
function bindPage(path){
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>go('/admin/employees/'+b.dataset.view)));
  document.querySelectorAll('[data-edit]').forEach(b=>b.addEventListener('click',()=>go('/admin/employees/'+b.dataset.edit+'/edit')));
  document.querySelectorAll('[data-delete]').forEach(b=>b.addEventListener('click',async()=>{const e=state.employeeCache.find(x=>x.id==b.dataset.delete);if(!confirm(`Delete ${e?.full_name||'this employee'}? This cannot be undone.`))return;try{await api('/api/admin/employees/'+b.dataset.delete,{method:'DELETE'});toast('Employee deleted.');render();}catch(err){toast(err.message);}}));
  if(path==='/admin/employees'){
    let timer;document.getElementById('employee-search')?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{listPage=1;render();},240);});
    ['department-filter','status-filter'].forEach(id=>document.getElementById(id)?.addEventListener('change',()=>{listPage=1;render();}));
    document.getElementById('prev-page')?.addEventListener('click',()=>{listPage=Math.max(1,listPage-1);render();});document.getElementById('next-page')?.addEventListener('click',()=>{listPage++;render();});
  }
  const empForm=document.getElementById('employee-form');if(empForm)empForm.addEventListener('submit',async ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(empForm));try{const id=empForm.dataset.id;const res=await api(id?'/api/admin/employees/'+id:'/api/admin/employees',{method:id?'PUT':'POST',body:JSON.stringify(d)});toast(res.message);go('/admin/employees/'+res.employee.id);}catch(e){showFormError(e.message);}});
  const profile=document.getElementById('profile-form');if(profile)profile.addEventListener('submit',async ev=>{ev.preventDefault();const d=Object.fromEntries(new FormData(profile));delete d.full_name;delete d.email;delete d.employee_code;delete d.department;delete d.designation;try{const res=await api('/api/profile',{method:'PUT',body:JSON.stringify(d)});toast(res.message);render();}catch(e){showFormError(e.message);}});
  const adminAccount=document.getElementById('admin-account-form');if(adminAccount)adminAccount.addEventListener('submit',async ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(adminAccount));if(data.new_password!==data.confirm_password){showFormError('New password and confirmation do not match.');return;}delete data.confirm_password;try{const result=await api('/api/admin/account',{method:'PUT',body:JSON.stringify(data)});state.user=result.user;state.csrf=result.csrf_token;toast(result.message);render();}catch(error){showFormError(error.message);}});
  const adminCreate=document.getElementById('admin-create-form');if(adminCreate)adminCreate.addEventListener('submit',async ev=>{ev.preventDefault();const data=Object.fromEntries(new FormData(adminCreate));if(data.password!==data.confirm_password){const box=document.getElementById('admin-create-error');box.textContent='Password confirmation does not match.';box.style.display='block';return;}try{const result=await api('/api/admin/accounts/admin',{method:'POST',body:JSON.stringify(data)});state.companyName=result.company_name;toast(result.message);render();}catch(error){const box=document.getElementById('admin-create-error');box.textContent=error.message;box.style.display='block';}});

}
window.addEventListener('popstate',render);
initialize();
